### ISSUE TITLE
Namespace name

### ISSUE THREAD

**Issue by franzliedke** [mtotheikle/flarum-recaptcha#1]
Hey, great to see you working on an extension for Flarum; this is looking good!

I'd suggest to use another namespace than `FlarumExtensions`, though - or at least use a subnamespace for this particular extension, in order to avoid conflicts in the future. :)

**Comment by mtotheikle** [comment]
Yes, I agree. This was just thrown together and couldn't think of good namespace to begin with.

I will be renaming this to recaptcha as well as updating the reference in some of the code. 

@tobscure mentioned including this in the core so I think the best namespace for this will just be `Flarum`.
