### ISSUE TITLE
Include build.sh script

### ISSUE THREAD

**Issue by mtotheikle** [mtotheikle/flarum-recaptcha#2]
This is helpful to package the extension up with all the compiled assets. Would like to get some feedback from @franzliedke and @tobscure on extension distribution, but I'd say having easy support for developers to create an archive of an extension that can then get uploaded to GitHub for users to download is good first step.

**Comment by franzliedke** [comment]
We'll work on something like this when building the extension repository. For now, please take care of packaging yourself. :)

**Comment by tobyzerner** [comment]
I did whip [this](http://flarum.org/docs/extend/distribution/) up (untested) while writing the docs as an example.
